insert into users (user_id, username, password, name, phone, job) values (1, 'gframe0', 'oK7*K**qIFY', 'Garfield Frame', '810-347-3014', 'Sales Associate');
insert into users (user_id, username, password, name, phone, job) values (2, 'smarginson1', 'cB8".5.y3jBT', 'Sheff Marginson', '811-538-6168', 'Design Engineer');
insert into users (user_id, username, password, name, phone, job) values (3, 'asteptow2', 'zF9$aaIU70AtZipm', 'Aimee Steptow', '665-993-7737', 'Software Engineer III');
insert into users (user_id, username, password, name, phone, job) values (4, 'oharries3', 'pC5|MtJ)klD1X', 'Odella Harries', '751-173-2596', 'Design Engineer');
insert into users (user_id, username, password, name, phone, job) values (5, 'idedman4', 'yM0$|`D%+hZN?RwC', 'Inglebert Dedman', '799-600-6414', 'Structural Analysis Engineer');
insert into users (user_id, username, password, name, phone, job) values (6, 'ueivers5', 'wR4"cIYfezt("U', 'Ursola Eivers', '998-624-6797', 'Chief Design Engineer');
insert into users (user_id, username, password, name, phone, job) values (7, 'arowston6', 'kT9<G3x".*{uL9O', 'Aldus Rowston', '349-869-6986', 'General Manager');
insert into users (user_id, username, password, name, phone, job) values (8, 'rauckland7', 'iY8''Qg_lv4m#8', 'Ranice Auckland', '734-162-9438', 'Geological Engineer');
insert into users (user_id, username, password, name, phone, job) values (9, 'jgotthard8', 'oV2?OAL,#fz.cs', 'Jimmie Gotthard', '491-756-0236', 'Health Coach IV');
insert into users (user_id, username, password, name, phone, job) values (10, 'twyke9', 'gV6=@RC+Sz2.r', 'Torrie Wyke', '268-460-3896', 'Dental Hygienist');

insert into boards (board_id, board_name, board_type) values (1, 'Kololo Airstrip', 'Comedy|Drama');
insert into boards (board_id, board_name, board_type) values (2, 'Olympia Regional Airport', 'Comedy|Horror|Sci-Fi');
insert into boards (board_id, board_name, board_type) values (3, 'Caiguna Airport', 'Comedy|Drama');
insert into boards (board_id, board_name, board_type) values (4, 'Rafael Cabrera Airport', 'Documentary');
insert into boards (board_id, board_name, board_type) values (5, 'Natuashish Airport', 'Action|Drama|Romance|Western');
insert into boards (board_id, board_name, board_type) values (6, 'Seward Airport', 'Action');
insert into boards (board_id, board_name, board_type) values (7, 'Chileka International Airport', 'Drama|Romance');
insert into boards (board_id, board_name, board_type) values (8, 'Masirah Air Base', 'Comedy');
insert into boards (board_id, board_name, board_type) values (9, 'Dadu West Airport', 'Comedy');
insert into boards (board_id, board_name, board_type) values (10, 'Surkhet Airport', 'Drama');
insert into boards (board_id, board_name, board_type) values (11, 'Kayseri Erkilet Airport', 'Horror|Thriller');
insert into boards (board_id, board_name, board_type) values (12, 'George Downer Airport', 'Comedy|Musical|Romance');
insert into boards (board_id, board_name, board_type) values (13, 'Joe Foss Field Airport', 'Action|Comedy');
insert into boards (board_id, board_name, board_type) values (14, 'Francisco Beltrão Airport', 'Comedy|Drama');
insert into boards (board_id, board_name, board_type) values (15, 'Tau Airport', 'Documentary');
insert into boards (board_id, board_name, board_type) values (16, 'Copenhagen Kastrup Airport', 'Drama|Musical');
insert into boards (board_id, board_name, board_type) values (17, 'Hagfors Airport', 'Documentary');
insert into boards (board_id, board_name, board_type) values (18, 'Lewistown Municipal Airport', 'Action|War');
insert into boards (board_id, board_name, board_type) values (19, 'Drake Field', 'Comedy|Fantasy');
insert into boards (board_id, board_name, board_type) values (20, 'Cap Haitien International Airport', 'Drama');
insert into boards (board_id, board_name, board_type) values (21, 'Loikaw Airport', 'Adventure|Comedy|Drama');
insert into boards (board_id, board_name, board_type) values (22, 'Sandy Lake Airport', 'Action|Comedy|Musical|Romance');
insert into boards (board_id, board_name, board_type) values (23, 'Kadapa Airport', 'Mystery|Thriller');
insert into boards (board_id, board_name, board_type) values (24, 'Jefferson City Memorial Airport', 'Crime|Drama|Horror');
insert into boards (board_id, board_name, board_type) values (25, 'San Cristóbal Airport', 'Drama|Thriller');
insert into boards (board_id, board_name, board_type) values (26, 'Tureia Airport', 'Horror');
insert into boards (board_id, board_name, board_type) values (27, 'Car Nicobar Air Force Station', 'Drama');
insert into boards (board_id, board_name, board_type) values (28, 'Gangneung Airport (K-18)', 'Documentary');
insert into boards (board_id, board_name, board_type) values (29, 'Bell Island Hot Springs Seaplane Base', 'Comedy|Documentary|Musical');
insert into boards (board_id, board_name, board_type) values (30, 'Junin Airport', 'Action|Adventure|Drama|War');
insert into boards (board_id, board_name, board_type) values (31, 'Port Hawkesbury Airport', 'Adventure|Animation|Children|Drama');
insert into boards (board_id, board_name, board_type) values (32, 'Turpan Jiaohe Airport', 'Comedy');
insert into boards (board_id, board_name, board_type) values (33, 'San Cristóbal Airport', 'Comedy|Romance');
insert into boards (board_id, board_name, board_type) values (34, 'Junin Airport', 'Documentary');
insert into boards (board_id, board_name, board_type) values (35, 'Albacete-Los Llanos Airport', 'Comedy');
insert into boards (board_id, board_name, board_type) values (36, 'Tri-State/Milton J. Ferguson Field', 'Drama|Mystery|Sci-Fi|Thriller');
insert into boards (board_id, board_name, board_type) values (37, 'Peretola Airport', 'Comedy|Romance');
insert into boards (board_id, board_name, board_type) values (38, 'Bomai Airport', 'Comedy|Drama|Romance');
insert into boards (board_id, board_name, board_type) values (39, 'Poitiers-Biard Airport', 'Comedy|Drama|Romance');
insert into boards (board_id, board_name, board_type) values (40, 'Copenhagen Roskilde Airport', 'Documentary');
insert into boards (board_id, board_name, board_type) values (41, 'Minhas Air Base', 'Animation');
insert into boards (board_id, board_name, board_type) values (42, 'Enyu Airfield', 'Crime|Drama');
insert into boards (board_id, board_name, board_type) values (43, 'Baimuru Airport', 'Comedy');
insert into boards (board_id, board_name, board_type) values (44, 'Jérémie Airport', 'Adventure|Children');
insert into boards (board_id, board_name, board_type) values (45, 'Misima Island Airport', 'Comedy|Fantasy|Romance');
insert into boards (board_id, board_name, board_type) values (46, 'Phitsanulok Airport', 'Action|Romance|Sci-Fi|Thriller');
insert into boards (board_id, board_name, board_type) values (47, 'Tilin Airport', 'Thriller');
insert into boards (board_id, board_name, board_type) values (48, 'Maribor Airport', 'Comedy|Drama');
insert into boards (board_id, board_name, board_type) values (49, 'Namlea Airport', 'Comedy');
insert into boards (board_id, board_name, board_type) values (50, 'Abu Dhabi International Airport', 'Horror');

